### ISSUE TITLE
Empty pot file produced

### ISSUE THREAD

**Issue by fi5u** [stephenharris/grunt-pot#2]
I am using _grunt-pot_ to help with WordPress development. However I cannot seem to get a pot file created with any content in, it always produces an empty pot file.

My grunt task looks like this:

```
    pot: {
        options: {
            text_domain: 'test_site',
            dest: '<%= yeoman.dev %>/languages/',
            keywords: ['__', '_e']
        },

        files:{
            src:  [ '<%= yeoman.app %>/{,*/{,*/}}*.php' ],
            expand: true
        }
    }
```

I know the `files`>`src` property is fine as the same one works for the watch task.
Here is an example of what I want extracting into the pot file:

```
<?php _e( 'That page cannot be found.', 'test_site' ); ?>
```

Have I got an option set wrong?
Many thanks

I'm using `grunt-pot` `0.1.1`

**Comment by davetayls** [comment]
It would be really nice to be able to specify the location of the `xgettext` command so the you don't have to have it in the path. is this possible?
